services:
  softioc_a:
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true
    # stdin_open: true
    hostname: softioca
    container_name: softioca
    volumes:
      - ./softioc_a.db:/db/softioc.db

  softioc_b:
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true
    # stdin_open: true
    hostname: softiocb
    container_name: softiocb
    volumes:
      - ./softioc_b.db:/db/softioc.db

  softioc_ramp:
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true
    # stdin_open: true
    hostname: softiocramp
    container_name: softiocramp
    volumes:
      - ./softioc_ramp.db:/db/softioc.db

  websocket-gateway:
    image: ghcr.io/bisegni/sciarc:main
    command: gateway
    ports:
      - 8000:8000