services:
  softioc_a:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    hostname: softioca
    container_name: softioca
    volumes:
      - ./softioc_a.db:/db/softioc.db
  softioc_b:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    hostname: softiocb
    container_name: softiocb
    volumes:
      - ./softioc_b.db:/db/softioc.db
  client:
    image: epics-base:1.0
    entrypoint: /bin/sh
    stdin_open: true
    tty: true 