apiVersion: v1
kind: Service
metadata:
  name: websocket-gateway--service
  labels:
    app: websocket-gateway
    kind: epics-ioc
spec:
  type: LoadBalancer
  selector:
    app: websocket-gateway
  ports:
    - name: http 
      protocol: TCP
      port: 8000
      targetPort: 8000