apiVersion: v1
kind: ConfigMap
metadata:
  name: softioc-b
  labels:
    kind: epics-ioc
data:
  softioc-b.db: |
    record(ao,"channel:b") {
        field(DTYP,"Soft Channel")
        field(HHSV,MAJOR)
        field(HIHI,1)
    } 